### PR TITLE
more logging

### PR DESCRIPTION
**Pull request by azylman**
I don't currently have a working dev environment so I haven't tested this (it might not compile), I wrote it in github's file editor UI

I was seeing "exit status 128" from some clones and wanted more info

### CODE REVIEW

**Comment by rgarcia** [comment]
You're also seeing it hang, right? Is this hang happening when you invoke reposync directly or is it salt hanging?

**Comment by azylman** [comment]
When I invoke reposync directly. I see a bunch of git clones start failing with "exit status 128" and then the whole thing hangs.

**Comment by rgarcia** [comment]
I can't reproduce this on master:

```
$ ssh-add -D # remove all ssh keys from ssh-agent
$ go run main.go -archivedir ./tmp/.archive -dir ./tmp -org Clever -token $GITHUB_API_TOKEN
<see a bunch of 128 exit codes>
<exits cleanly>
```

**Comment by azylman** [comment]
So that means that the 128 exit codes aren't related, but I'd still like to know what they are.

**Comment by rgarcia** [comment]
Yeah, not trying to contest that, just trying to figure out the hang. I'll merge/publish this, thanks.

**Comment by azylman** [comment]
@rgarcia thanks for the help, that's useful info

**Comment by rgarcia** [comment]
0.6.2 published https://github.com/rgarcia/reposync/releases

**Pull request merged**
